### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [Vera-Evdokimova/ciphxor#1]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

шифрация
Шифрация (-c) или дешифрация (-d) указанного (в аргументе командной строки) файла. Выходной файл указывается как -o filename.txt, по умолчанию имя формируется из имени входного файла с добавлением расширения.
Алгоритм шифрации XOR. Ключ указывается после -c или -d в шестнадцатеричной системе, длина ключа -- любое целое количество байт.

Command Line: ciphxor [-c key] [-d key] inputname.txt [-o outputname.txt]

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Рекомендуется следующий подход к разработке**:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by JohnKhandygo** [comment]
В принципе все замечательно, надо исправить несколько мелочей:
- [x] Ошибка в описании ключей для `CommandLineOptions::outputFilename`.
- [ ] Считается просто [супер плохим тоном](http://wiki.c2.com/?ConstructorDoesTheWork) делать какую-то реальную работу внутри конструктора класса. Конструктор предназначен для инициализации состояния экземпляра класса и ни для чего больше. 
- [x] Все содержимое файла считывается целиком в память программы. Это не очень эффективно, учитывая, что при больших объемах файлов программа может упасть из-за нехватки памяти. Вам необходимо считывать файл по кусочкам, обрабатывать каждый кусочек отдельно и сразу записывать его. 
- [x] Не обрабатывается ситуация нечетной длины ключа шифрования. Ну и в принципе не очень понятно, что будет, если в ключе какую-нибудь дребедень написать (см. [описание метода `Character::digit`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#digit(char,%20int))). Все такие ситуации должны быть покрыты в тестах.
- [x] А нельзя ли избавиться от переменной `key` внутри метода `encrypt`?
- [x] По условию задания необходимо было разработать инструкцию/скрипты сборки и запуска программы из командной строки.

**Comment by Vera-Evdokimova** [comment]
Поправила...

**Comment by JohnKhandygo** [comment]
У Вас до сих пор основная работа (вызов метода `CipherXOR::encrypt`) происходит в конструкторе. Еще раз: это очень-очень плохо. Так делать нельзя. Исправьте.

**Comment by Vera-Evdokimova** [comment]
Вроде исправила.

**Comment by Vera-Evdokimova** [comment]
Задание в итоге закрыто или нет?

**Comment by JohnKhandygo** [comment]
Да, закрыто.
