### ISSUE TITLE
Next task 

### ISSUE THREAD

**Issue by JohnKhandygo** [Vera-Evdokimova/ciphxor#2]
Вам осталось не так много исправить по второму заданию, поэтому предлагаю подумать над условием третьего. Есть несколько вариантов:
1. Получаете стандартное третье задание на написание графического приложения на Swing/JavaFX
2. Можете придумать свой вариант графического приложения, мы его обсудим и дополним/упростим по необходимости. По сложности должно получиться что-то типа многопользовательских шашек на одном компьютере.
3. Если Вам интересны какие-то конкретные направление в программировании (например, базы данных, web, Android) можно попробовать придумать задание с использованием этих технологий. 

Какой вариант Вам нравится больше всего?

**Comment by Vera-Evdokimova** [comment]
Первый

**Comment by JohnKhandygo** [comment]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Реверси**
Реализовать игру Реверси для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Реверси).

**Comment by Vera-Evdokimova** [comment]
https://github.com/Vera-Evdokimova/Reversi
